AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Shared Services Template

Parameters:
  WFName:
    Type: String

  CFTemplateS3Path:
    Type: String

  Environment:
    Type: String
    AllowedValues: [dev, test, prod]
    Default: dev

Resources:

  ECRReposTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub ${CFTemplateS3Path}/step_020_01_ecr_repos.yaml
      Parameters:
        WFName: !Ref WFName
        CFTemplateS3Path: !Ref CFTemplateS3Path
        Environment: dev