AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Urban Insitute Workflow Security Groups

Parameters:

  WFName:
    Type: String

  VPCId:
    Description: "ID of the VPC to build Security Groups in"
    Type: AWS::EC2::VPC::Id

  Environment:
    Type: String
    AllowedValues: [dev, test, prod]

  CFTemplateS3Path:
    Type: String

  VPCCIDR:
    Description: "The IP CIDR of your source IP Addres"
    Type: String
    MinLength: 9
    MaxLength: 18
    AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
    ConstraintDescription: "This must be a valid CIDR range in form of x.x.x.x/x"

