AWSTemplateFormatVersion: 2010-09-09

Description: >-
  ECR Repos, currently containing data processing repos

Parameters:
  WFName:
    Type: String

  CFTemplateS3Path:
    Type: String

  Environment:
    Type: String
    AllowedValues: [dev, test, prod]
    Default: dev

Resources:
  LidarProcessingECRRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
              "rules": [
                  {
                      "rulePriority": 1,
                      "description": "Expire images older than 14 days",
                      "selection": {
                          "tagStatus": "untagged",
                          "countType": "sinceImagePushed",
                          "countUnit": "days",
                          "countNumber": 14
                      },
                      "action": {
                          "type": "expire"
                      }
                  }
              ]
          }
      RepositoryName: !Sub repo-${WFName}-${Environment}-lidarprocessing
      RepositoryPolicyText: |
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Sid": "codebuild_policy",
              "Effect": "Allow",
              "Principal": {
                "Service": "codebuild.amazonaws.com"
              },
              "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer"
              ]
            }
          ]
        }
      Tags:
        - Key: Name
          Value: !Sub repo-${WFName}-${Environment}-lidarprocessing

  #PGAdmin webservice repo, as a means to use Fargate to host PgAdmin service
  PgAdminECRRepo:
    Type: "AWS::ECR::Repository"
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
              "rules": [
                  {
                      "rulePriority": 1,
                      "description": "Expire images older than 14 days",
                      "selection": {
                          "tagStatus": "untagged",
                          "countType": "sinceImagePushed",
                          "countUnit": "days",
                          "countNumber": 14
                      },
                      "action": {
                          "type": "expire"
                      }
                  }
              ]
          }
      RepositoryName: !Sub repo-${WFName}-${Environment}-pgadmin
      RepositoryPolicyText: |
        {
          "Version": "2008-10-17",
          "Statement": [
            {
              "Sid": "codebuild_policy",
              "Effect": "Allow",
              "Principal": {
                "Service": "codebuild.amazonaws.com"
              },
              "Action": [
                "ecr:BatchCheckLayerAvailability",
                "ecr:BatchGetImage",
                "ecr:GetDownloadUrlForLayer"
              ]
            }
          ]
        }
      Tags:
        - Key: Name
          Value: !Sub repo-${WFName}-${Environment}-pgadmin
Outputs:

  LidarProcessingECRRepoArn:
    Value: !GetAtt LidarProcessingECRRepo.Arn
    Export:
      Name: !Sub repo-${WFName}-${Environment}-lidarprocessing-arn

  LidarProcessingECRRepoName:
    Value: !Ref LidarProcessingECRRepo
    Export:
      Name: !Sub repo-${WFName}-${Environment}-lidarprocessing-name

  PgAdminECRRepoArn:
    Value: !GetAtt PgAdminECRRepo.Arn
    Export:
      Name: !Sub repo-${WFName}-${Environment}-pgadmin-arn

  PgAdminECRRepoName:
    Value: !Ref PgAdminECRRepo
    Export:
      Name: !Sub repo-${WFName}-${Environment}-pgadmin-name