AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Urban Institute workflows:
  * Compute resources: any ECR or EC2 cluster
  * Repo resources: ECR Container repo and code commit resources
  * Data pipelines
  * Databases
  * Sagemaker/Jupyter notebooks

Parameters:
  WFName:
    Type: String

  CFTemplateS3Path:
    Type: String

  Environment:
    Type: String
    AllowedValues: [dev, test, prod]
    Default: dev

Resources:

  ECRReposTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub ${CFTemplateS3Path}/step_020_01_ecr_repos.yaml
      Parameters:
        WFName: !Ref WFName
        CFTemplateS3Path: !Ref CFTemplateS3Path
        Environment: dev

  #create the ECR Fargate cluster to run any thing significant
  #at the present time, we will only create a fargate cluster to run any data processing job
  ECRClusterResourcesTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub ${CFTemplateS3Path}/step_020_02_ecr_clusters.yaml
      Parameters:
        WFName: !Ref WFName
        CFTemplateS3Path: !Ref CFTemplateS3Path
        Environment: dev

  ECRTasksAndServicesTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub ${CFTemplateS3Path}/step_020_03_ecr_tasks_and_services.yaml
      Parameters:
        WFName: !Ref WFName
        CFTemplateS3Path: !Ref CFTemplateS3Path
        Environment: dev