AWSTemplateFormatVersion: 2010-09-09

Description: >-
  Shared Services Template

Parameters:
  CFTemplateS3Path:
    Type: String
    Default: https://s3.amazonaws.com/cf-templates-j3atw72be18l-us-east-1/sharedservices-useast1-cf-templates

  Environment:
    Type: String
    Default: prod

  CreateCommDebug:
    Type: String
    Default: false
    AllowedValues: [true, false]

  CloudFormationS3Bucket:
    Type: String
    Default: cf-templates-j3atw72be18l-us-east-1

Conditions:
  CreateCommDebugCondition: !Equals [ !Ref CreateCommDebug, true ]

Resources:

  VPCTemplate:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL:
        !Sub ${CFTemplateS3Path}/step_020_01_instantiate_shared_services_vpc.yaml
      Parameters:
        Environment: !Ref Environment
        CFTemplateS3Path: !Ref CFTemplateS3Path